### PR TITLE
[fix] Github URL

### PR DESCRIPTION
**Pull request by rvalitov**
Fixes invalid link to Github repo.

### CODE REVIEW

**Review by nikosdion — APPROVED** [review]

**Comment by nikosdion** [comment]
Thank you! The `composer.json` was written before I created the GitHub repo. Oops!

**Comment by rvalitov** [comment]
Sorry, I thought you merged it already 🤦

**Comment by rvalitov** [comment]
I guess I can reopen it

**Comment by nikosdion** [comment]
No worries, I applied the changes manually :)

**Comment by rvalitov** [comment]
I would like to contribute more. Do you plan to add your repositories for the Hacktoberfest event?

**Comment by nikosdion** [comment]
@rvalitov I welcome contributions :)

Unfortunately, we do not plan on having any repositories on Hacktoberfest for two reasons.

The first reason is that October is extremely busy for us, since new Joomla versions come out in the middle of October every year. We spend the first half ensuring no last minute Joomla changes broke our software, and the latter half doing support as people invariably think that any unrelated issue has something to do with their updating the CMS on their site.

The second reason is that Hacktoberfest encourages quantity, not quality. This results in a lot of contributions which are either trivial or outright wrong, from contributors which are unlikely to be responsive to communication. This sucks up maintainer time without providing any real benefits to the code base, therefore having a negative net value for the users of the software.

You are welcome to contribute whenever you want. You don't have to limit yourself to Hacktoberfest. After all, recruiters and interviewers will look at the whole of your public contributions and sample the quality and impact of them. None of them cares about Hacktoberfest. They might care about something like Google Summer Of Code which is more like an internship, but that's about it.

**Pull request closed without merging**
